import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Head from "next/head";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head>
    //if stylesheet put it in the header
      </Head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Script
          src="https://cdn.jsdelivr.net/npm/p5@1.11.3/lib/p5.min.js"
          strategy="beforeInteractive"
        ></Script>
        {/* <Script
          src="https://cdn.jsdelivr.net/npm/p5@1.11.3/lib/addons/p5.dom.min.js"
          strategy="beforeInteractive"
        ></Script> */}
        {/* <Script
          src="https://unpkg.com/p5.js-svg@1.6.0"
          strategy="beforeInteractive"
        ></Script> */}
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/opentype.js/0.6.5/opentype.min.js"
          strategy="beforeInteractive"
        ></Script>
        <Script
          src="https://cdn.rawgit.com/nodebox/g.js/master/dist/g.min.js"
          strategy="beforeInteractive"
        ></Script>

        {children}
      </body>
    </html>
  );
}
